on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install Project
      run: npm install
        
    - name:  Test Project
      run: npm run test
        
    - name:  Build Project
      run: npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server:  ftp.itqanesoft.com
        username: hamlilic
        password: ${{ secrets.ftp_itqanesoft_password }}
        local-dir: dist/cafee/
        server-dir: /public_html/
